# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Dev Containers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: weekly

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/docker"
    schedule:
      interval: weekly
